// Project data for Carlos Carbonell
const projects = [
  {
    id: 32,
    title: 'Le Snake',
    category: 'Campaign',
    brand: 'Asensi Studio',
    image: 'files/le-snake.webp',
    alt: 'Le Snake - Campaign for Asensi Studio directed by Hector Sanchis & shot by Carlos Carbonell',
    gif: 'files/le-snake.webm',
    year: '2025',
    location: 'Valencia, Spain',
    format: 'Pyxis LF & AstroHori Probe 18mm',
    vimeoId: '1083120450',
    url: 'le-snake.html',
    director: 'Hector Sanchis',
    productionCompany: 'undefined',
  },
  {
    id: 31,
    title: 'Le fleur',
    category: 'Campaign',
    brand: 'Asensi Studio',
    image: 'files/le-fleur.webp',
    alt: 'Le Fleur - Campaign for Asensi Studio directed by Hector Sanchis & shot by Carlos Carbonell',
    gif: 'files/le-fleur.webm',
    year: '2025',
    location: 'Valencia, Spain',
    format: 'Bolex Rex 2 KV3 7207',
    vimeoId: '1083120844',
    url: 'le-fleur.html',
    director: 'Hector Sanchis',
    productionCompany: 'undefined',
  },
  {
    id: 30,
    title: 'El fútbol es solo fútbol',
    category: 'Campaign',
    brand: 'Levante UD',
    image: 'files/el-futbol-es-solo-futbol.webp',
    alt: 'El fútbol es solo fútbol - Campaign for Levante UD directed by David García Yuste & shot by Carlos Carbonell',
    gif: 'files/el-futbol-es-solo-futbol.webm',
    year: '2025',
    location: 'Valencia, Spain',
    format: 'Pyxis LF & Leica R',
    vimeoId: '1083124803',
    url: 'el-futbol-es-solo-futbol.html',
    director: 'David García Yuste',
    productionCompany: 'Nyàs',
  },
  {
    id: 29,
    title: 'Verte',
    category: 'Campaign',
    brand: 'Visit Valencia',
    image: 'files/verte.webp',
    alt: 'Verte - Campaign for Visit Valencia directed by Júlia Castaño & shot by Carlos Carbonell',
    gif: 'files/verte.webm',
    year: '2024',
    location: 'Valencia, Spain',
    format: 'Alexa Mini & Zeiss SUPER SPEED MKii',
    vimeoId: '1044991483',
    url: 'verte.html',
    director: 'Júlia Castaño',
    productionCompany: 'Nyàs',
  },
  {
    id: 28,
    title: 'Maratón Valencia',
    category: 'Campaign',
    brand: '42K running',
    image: 'files/maraton.webp',
    alt: 'Maratón Valencia - Campaign for 42K running directed by Hector Sanchis & shot by Carlos Carbonell',
    gif: 'files/maraton.webm',
    year: '2024',
    location: 'Valencia, Spain',
    format: 'Pyxis LF & Blazar Remus',
    vimeoId: '1083118380',
    url: 'maraton.html',
    director: 'Hector Sanchis',
    productionCompany: 'undefined',
  },
  {
    id: 27,
    title: 'Rebobinar',
    category: 'Music video',
    brand: 'La Fúmiga',
    image: 'files/rebobinar.webp',
    alt: 'Rebobinar - Music video for La Fúmiga directed by Artur Martínez & shot by Carlos Carbonell',
    gif: 'files/rebobinar.webm',
    year: '2024',
    location: 'Costa blanca, Spain',
    format: 'Pyxis LF & Leica R',
    vimeoId: '1037767067',
    url: 'rebobinar.html',
    director: 'Artur Martínez',
    productionCompany: 'Bondó',
  },
  {
    id: 26,
    title: 'ORO',
    category: 'Music video',
    brand: 'Boira',
    image: 'files/oro.webp',
    alt: 'ORO - Music video for Boira directed by David García Yuste & shot by Carlos Carbonell',
    gif: 'files/oro.webm',
    year: '2024',
    location: 'Valencia, Spain',
    format: 'Bolex Rex 3 KV3 7219',
    vimeoId: '1083136168',
    url: 'oro.html',
    director: 'David García Yuste',
    productionCompany: 'Nyàs',
  },
  {
    id: 25,
    title: "L'espurna D'aielo",
    category: 'Short Film',
    brand: 'Documentary',
    image: 'files/aielo.webp',
    alt: "L'espurna D'aielo - Documentary directed by Óscar Jimenez & shot by Carlos Carbonell",
    gif: 'files/aielo.webm',
    year: '2024',
    location: 'Aielo del Malferit, Valencia',
    format: 'BMPCC & Leica R',
    vimeoId: '1084924237',
    url: 'lespurna-de-aielo.html',
    director: 'Óscar Jimenez',
    productionCompany: 'La Veu media',
    overlayImages: [
      'files/espurna-laurel-1.webp',
      'files/espurna-laurel-2.webp',
      'files/espurna-laurel-3.webp',
      'files/espurna-laurel-4.webp',
    ]
  },
  {
    id: 24,
    title: 'Nos volveremos a ver',
    category: 'Campaign',
    brand: 'La Raiz',
    image: 'files/nos-volveremos-a-ver.webp',
    alt: 'Nos volveremos a ver - Campaign for La Raiz directed by Nyàs & shot by Carlos Carbonell',
    gif: 'files/nos-volveremos-a-ver.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'Alexa Mini & Leica R',
    vimeoId: '910848799',
    url: 'nos-volveremos-a-ver.html',
    director: 'Nyàs',
    productionCompany: 'Nyàs',
  },
  {
    id: 23,
    title: 'La mala reputación',
    category: 'Music video',
    brand: 'Ciudad Jara',
    image: 'files/mala-reputacion.webp',
    alt: 'La mala reputación - Music video for Ciudad Jara',
    gif: 'files/mala-reputacion.webm',
    year: '2024',
    location: 'Valencia, Spain',
    format: 'ARRI ALEXA MINI & LEICA R',
    vimeoId: '884878570',
    url: 'mala-reputacion.html',
    director: 'Júlia Castaño',
    productionCompany: 'Nyàs',
  },
  {
    id: 22,
    title: 'Pa Casa',
    category: 'Music video',
    brand: 'Saiko x Ryan Castro',
    image: 'files/pa-casa.webp',
    alt: 'Pa Casa - Music video for Saiko x Ryan Castro directed by Jorge No & shot by Carlos Carbonell',
    gif: 'files/pa-casa.webm',
    year: '2023',
    location: 'Mallorca, Balears',
    format: 'Alexa Mini & Zeiss SUPER SPEED MKii',
    vimeoId: '898735685',
    url: 'pa-casa.html',
    director: 'Jorge No',
    productionCompany: 'Take a Nap',
  },
  {
    id: 21,
    title: 'Dimonis',
    category: 'Short Film',
    brand: 'concept film',
    image: 'files/dimonis.webp',
    alt: 'Dimonis - Short Film concept directed by Carlos Carbonell & shot by Carlos Carbonell',
    gif: 'files/dimonis.webm',
    year: '2023',
    location: 'Campanar, Valencia',
    format: '8MM',
    vimeoId: '892874228',
    url: 'dimonis.html',
    director: 'Carlos Carbonell',
    productionCompany: 'Nyàs',
  },
  {
    id: 20,
    title: 'Llençols',
    category: 'Short Film',
    brand: 'concept film',
    image: 'files/llencols.webp',
    alt: 'Llençols - Short Film concept directed by Júlia Castaño & shot by Carlos Carbonell',
    gif: 'files/llencols.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: '8mm, digital, tape',
    vimeoId: '889986521',
    url: 'llencols.html',
    director: 'Júlia Castaño',
    productionCompany: 'Nyàs',
  },
  {
    id: 19,
    title: 'El primer ball',
    category: 'Music video',
    brand: 'El Diluvi ft. Els Catarres',
    image: 'files/el-primer-ball.webp',
    alt: 'El primer ball - Music video for El Diluvi ft. Els Catarres directed by Júlia Castaño & shot by Carlos Carbonell',
    gif: 'files/el-primer-ball.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'Zcam & Leica R',
    vimeoId: '842542002',
    url: 'el-primer-ball.html',
    director: 'Júlia Castaño',
    productionCompany: 'Nyàs',
  },
  {
    id: 18,
    title: 'Tu fiel Jodida Mitad',
    category: 'Music video',
    brand: 'Sienna',
    image: 'files/tu-fiel-jodida-mitad.webp',
    alt: 'Tu fiel Jodida Mitad - Music video for Sienna directed by Charlie Gradolí & shot by Carlos Carbonell',
    gif: 'files/tu-fiel-jodida-mitad.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'BMPCC & Angenieux HR',
    vimeoId: '840345055',
    url: 'tu-fiel-jodida-mitad.html',
    director: 'Charlie Gradolí',
    productionCompany: 'Nyàs',
  },
  {
    id: 17,
    title: 'Office Rats',
    category: 'Campaign',
    brand: 'Issues',
    image: 'files/office-rats.webp',
    alt: 'Office Rats - Campaign for Issues directed by Charlie Gradolí & shot by Carlos Carbonell',
    gif: 'files/office-rats.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'BMPCC & Leica R',
    vimeoId: '795757403',
    url: 'office-rats.html',
    director: 'Charlie Gradolí',
    productionCompany: 'Nyàs',
  },
  {
    id: 16,
    title: 'No es diumenge',
    category: 'Music video',
    brand: 'Pupil·les',
    image: 'files/no-es-diumenge.webp',
    alt: 'No es diumenge - Music video for Pupil·les directed by Júlia Castaño & shot by Carlos Carbonell',
    gif: 'files/no-es-diumenge.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'BMPCC & Super Takumar',
    vimeoId: '808413490',
    url: 'no-es-diumenge.html',
    director: 'Júlia Castaño',
    productionCompany: 'Nyàs',
  },
  {
    id: 15,
    title: 'Hijos de la Voluntad',
    category: 'Short Film',
    brand: 'Short film ',
    image: 'files/hijos-de-la-voluntad.webp',
    alt: 'Hijos de la Voluntad - Short Film directed by Antonio Galicia & shot by David García Yuste',
    gif: 'files/hijos-de-la-voluntad.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'K3 16mm Orwo film',
    vimeoId: '847746257',
    url: 'hijos-de-la-voluntad.html',
    director: 'Antonio Galicia',
    productionCompany: 'David García Yuste',
    overlayImages: [
      'files/hdlv-laurel-1.webp',
      'files/hdlv-laurel-2.webp',
      'files/hdlv-laurel-3.webp'
    ]
  },
  {
    id: 14,
    title: 'Rally',
    category: 'Music video',
    brand: 'Treze',
    image: 'files/rally.webp',
    alt: 'Rally - Music video for Treze directed by Charlie Gradolí & shot by Carlos Carbonell',
    gif: 'files/rally.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'mini DV tape / BMPCC & Leica R',
    vimeoId: '808412621',
    url: 'rally.html',
    director: 'Charlie Gradolí',
    productionCompany: 'Nyàs',
  },
  {
    id: 13,
    title: 'Clasicos FS23',
    category: 'Campaign',
    brand: 'Clasicos del barrio',
    image: 'files/clasicos.webp',
    alt: 'Clasicos FS23 - Campaign for Clasicos del barrio directed by David García Yuste & shot by Carlos Carbonell',
    gif: 'files/clasicos.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'BMPCC & Leica R',
    vimeoId: '840344327',
    url: 'clasicos-fs23.html',
    director: 'David García Yuste',
    productionCompany: 'Nyàs',
  },
  {
    id: 12,
    title: 'A fer la mà',
    category: 'Music video',
    brand: 'El diluvi',
    image: 'files/a-fer-la-ma.webp',
    alt: 'A fer la mà - Music video for El diluvi directed by Charlie Gradolí & shot by Carlos Carbonell',
    gif: 'files/a-fer-la-ma.webm',
    year: '2023',
    location: 'Valencia, Spain',
    format: 'BMPCC & Leica R',
    vimeoId: '796578424',
    url: 'a-fer-la-ma.html',
    director: 'Charlie Gradolí',
    productionCompany: 'Nyàs',
  },
  {
    id: 11,
    title: 'Cantantes',
    category: 'Music video',
    brand: 'Ciudad Jara',
    image: 'files/cantantes.webp',
    alt: 'Cantantes - Music video for Ciudad Jara directed by Pablo Sanchez & shot by Carlos Carbonell',
    gif: 'files/cantantes.webm',
    year: '2022',
    location: 'Valencia, Spain',
    format: 'Zcam & Leica R',
    vimeoId: '675055836',
    url: 'cantantes.html',
    director: 'Pablo Sanchez',
    productionCompany: 'Nyàs',
  },
  {
    id: 10,
    title: 'Caliu',
    category: 'Short Film',
    brand: 'concept film',
    image: 'files/caliu.webp',
    alt: 'Caliu - Short Film concept directed by David García Yuste & shot by Carlos Carbonell',
    gif: 'files/caliu.webm',
    year: '2022',
    location: 'Mallorca, Balears',
    format: '8mm / BMPCC & Tokina RMC',
    vimeoId: '705442712',
    url: 'caliu.html',
    director: 'David García Yuste',
    productionCompany: 'Nyàs',
  },
  {
    id: 9,
    title: 'Si tu me pidieras',
    category: 'Music video',
    brand: 'Ciudad Jara',
    image: 'files/si-tu-me-pidieras.webp',
    alt: 'Si tu me pidieras - Music video for Ciudad Jara directed by Pablo Sanchez & shot by Carlos Carbonell',
    gif: 'files/si-tu-me-pidieras.webm',
    year: '2022',
    location: 'Valencia, Spain',
    format: 'Zcam & Leica R',
    vimeoId: '684623619',
    url: 'si-tu-me-pidieras.html',
    director: 'Pablo Sanchez',
    productionCompany: 'Nyàs',
  },
  {
    id: 8,
    title: 'Algo más fuerte',
    category: 'Music video',
    brand: 'Sienna',
    image: 'files/algo-mas-fuerte.webp',
    alt: 'Algo más fuerte - Music video for Sienna directed by Alex Sienna & shot by Carlos Carbonell',
    gif: 'files/algo-mas-fuerte.webm',
    year: '2021',
    location: 'Valencia, Spain',
    format: 'TAPE / BMPCC & Tokina RMC',
    vimeoId: '661024815',
    url: 'como-has-podido.html',
    director: 'Alex Sienna',
    productionCompany: 'Nyàs',
  },
  {
    id: 7,
    title: 'Adiós',
    category: 'Music video',
    brand: 'Ciudad Jara',
    image: 'files/adios.webp',
    alt: 'Adiós - Music video for Ciudad Jara directed by David García Yuste & shot by Carlos Carbonell',
    gif: 'files/adios.webm',
    year: '2022',
    location: 'Lisboa, Portugal',
    format: 'BMCC 4K & Contax Zeiss',
    vimeoId: '678603913',
    url: 'adios.html',
    director: 'David García Yuste',
    productionCompany: 'Nyàs',
  },
  {
    id: 6,
    title: 'Como has podido',
    category: 'Music video',
    brand: 'Sienna',
    image: 'files/como-has-podido.webp',
    alt: 'Como has podido - Music video for Sienna directed by Alex Sienna & shot by Carlos Carbonell',
    gif: 'files/como-has-podido.webm',
    year: '2021',
    location: 'Valencia, Spain',
    format: 'BMPCC & Contax Zeiss',
    vimeoId: '627606932',
    url: 'como-has-podido.html',
    director: 'Alex Sienna',
    productionCompany: 'undefined',
  },
  {
    id: 5,
    title: 'El Estreno',
    category: 'Short Film',
    brand: 'Short film ',
    image: 'files/el-estreno.webp',
    alt: 'El Estreno - Short Film directed by Júlia Castaño & Antonio Galicia & shot by Carlos Carbonell',
    gif: 'files/el-estreno.webm',
    year: '2021',
    location: 'Valencia & Gandia',
    format: 'BMPCC & Tokina RMC',
    vimeoId: '747769429',
    url: 'el-estreno.html',
    director: 'Júlia Castaño & Antonio Galicia',
    productionCompany: 'El Ático',
    overlayImages: [
      'files/el-estreno_laurel.webp'
    ]
  },
  {
    id: 4,
    title: 'Quiero que aparezcas aquí',
    category: 'Music video',
    brand: 'Sienna',
    image: 'files/quiero-que-aparezcas-aqui.webp',
    alt: 'Quiero que aparezcas aquí - Music video for Sienna directed by Alex Sienna & shot by Carlos Carbonell',
    gif: 'files/quiero-que-aparezcas-aqui.webm',
    year: '2021',
    location: 'Valencia, Spain',
    format: 'BMPCC & Tokina RMC',
    vimeoId: '661023923',
    url: 'quiero-que-aparezcas-aqui.html',
    director: 'Alex Sienna',
    productionCompany: 'undefined',
  },
  {
    id: 3,
    title: 'Season S21',
    category: 'Campaign',
    brand: 'BLGR',
    image: 'files/blgr.webp',
    alt: 'Season S21 - Campaign for BLGR directed by Manel Dart & shot by Carlos Carbonell',
    gif: 'files/blgr.webm',
    year: '2021',
    location: 'Valencia, Spain',
    format: 'BMPCC & Tokina RMC',
    vimeoId: '583027976',
    url: 'blgr-s21.html',
    director: 'Manel Dart',
    productionCompany: 'Cosas',
  },
  {
    id: 2,
    title: 'Esto me va a matar',
    category: 'Music video',
    brand: 'Sienna',
    image: 'files/esto-me-va-a-matar.webp',
    alt: 'Esto me va a matar - Music video for Sienna directed by Alex Sienna & shot by Carlos Carbonell',
    gif: 'files/esto-me-va-a-matar.webm',
    year: '2021',
    location: 'Valencia, Spain',
    format: 'Bolex rex4 KV3 7219',
    vimeoId: '566989443',
    url: 'esto-me-va-a-matar.html',
    director: 'Alex Sienna',
    productionCompany: 'undefined',
  },
  {
    id: 1,
    title: 'Bad Year',
    category: 'Short Film',
    brand: 'Concept Film',
    image: 'files/bad-year.webp',
    alt: 'Bad Year - Short Film concept directed by David García Yuste & shot by Carlos Carbonell',
    gif: 'files/bad-year.webm',
    year: '2021',
    location: 'Alboraya & Valencia',
    format: 'BMPCC & Tokina RMC',
    vimeoId: '561727684',
    url: 'bad-year.html',
    director: 'David García Yuste',
  },
];

export default projects;

// PROJECT SLUG EXTRACTION
const pathMatch = window.location.pathname.match(/^\/project\/([a-zA-Z0-9\-_]+)/);
const projectSlug = pathMatch ? pathMatch[1] : null;

// PROJECT LOOKUP
let project;
if (projectSlug) {
  project = projects.find(p => p.url.replace('.html', '') === projectSlug);
} else {
  const urlParams = new URLSearchParams(window.location.search);
  const projectId = parseInt(urlParams.get('id'), 10);
  if (!isNaN(projectId)) {
    project = projects.find((p) => p.id === projectId);
  }
}

// PROJECT DATA INJECTION
if (project) {
  document.getElementById('project-title').textContent = project.title;
  document.getElementById('project-details').textContent = `${project.year} | ${project.format} | ${project.location}`;
  document.getElementById('vimeo-player').src = `https://player.vimeo.com/video/${project.vimeoId}`;
  const description = `${project.title} - Directed by ${project.director}${project.productionCompany && project.productionCompany !== 'undefined' ? `, produced by ${project.productionCompany}` : ''}, a ${project.category.toLowerCase()} shot in ${project.location} (${project.year}), shot on ${project.format}, by Carlos Carbonell.`;
  document.getElementById('dynamic-description').setAttribute('content', description);
  const keywords = `${project.title}, ${project.brand}, ${project.category}, ${project.location}, Carlos Carbonell, cinematographer`;
  document.getElementById('dynamic-keywords').setAttribute('content', keywords);
  document.getElementById('og-title').setAttribute('content', project.title);
  document.getElementById('og-description').setAttribute('content', description);
  document.getElementById('og-image').setAttribute('content', project.image || '/default-thumbnail.jpg');
  document.getElementById('og-url').setAttribute('content', window.location.href);
} else {
  console.error('Project not found');
}